version: '3.8'

networks:
  kong-net:
    external: false

volumes:
  kong_data: {}

services:
  kong-database:
    image: postgres:16.2
    container_name: kong-database
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    volumes:
      - kong_data:/var/lib/postgresql/data
    networks:
      - kong-net
    
  kong-migration:
    image: custom-gateway:1.0
    container_name: kong-migration
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    networks:
      - kong-net
    depends_on:
      - kong-database
    command: kong migrations bootstrap
  
  kong:
    image: custom-gateway:1.0
    build: .
    container_name: kong
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
    volumes:
      - ./kong.conf:/etc/kong/kong.conf
    networks:
      - kong-net
    depends_on:
      - kong-database
      - kong-migration
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "9080:9080"
      - "9081:9081"
      - "8002:8002"