apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-collaboration
  labels:
    app: drawn-collaboration-service
spec:
  selector:
    matchLabels:
      app: drawn-collaboration-service
  replicas: 1
  template:
    metadata:
      labels:
        app: drawn-collaboration-service
    spec:
      containers:
      - name: drawn-collaboration-service
        image: sorawit12535/drawn-collaboration-service:1.0.5
        ports:
        - containerPort: 8083
        env:
        - name: DATABASE_URL
          value: ???
        - name: FIREBASE_API_KEY
          value: ???
        - name: FIREBASE_AUTH_DOMAIN
          value: ???
        - name: FIREBASE_PROJECT_ID
          value: ???
        - name: FIREBASE_STORAGE_BUCKET
          value: ???
        - name: FIREBASE_MESSAGING_SENDER_ID
          value: ???
        - name: FIREBASE_APP_ID
          value: ???
        - name: REDIS_HOST
          value: redis-server
        - name: REDIS_PORT
          value: "6379"
        - name: WORKSPACE_BACKEND_URL
          value: http://drawn-workspace-management-service:3001

---

apiVersion: v1
kind: Service
metadata:
  name: drawn-collaboration-service
spec:
  type: ClusterIP
  selector:
    app: drawn-collaboration-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
