apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-frontend
  labels:
    app: drawn-frontend
spec:
  selector:
    matchLabels:
      app: drawn-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: drawn-frontend
    spec:
      containers:
      - name: drawn-frontend
        image: sorawit12535/drawn-frontend:1.1.6
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: drawn-frontend
spec:
  selector:
    app: drawn-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
