apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api-gateway
  labels:
    app: drawn-api-gateway
spec:
  selector:
    matchLabels:
      app: drawn-api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: drawn-api-gateway
    spec:
      containers:
      - name: drawn-api-gateway
        image: sorawit12535/drawn-api-gateway:1.1.2
        ports:
        - containerPort: 8000
        - containerPort: 8002
        env:
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8001, 0.0.0.0:8444 ssl
        - name: KONG_PROXY_LISTEN
          value: 0.0.0.0:8000, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl
        - name: KONG_ADMIN_GUI_LISTEN
          value: 0.0.0.0:8002

---

apiVersion: v1
kind: Service
metadata:
  name: drawn-api-gateway
spec:
  selector:
    app: drawn-api-gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
    - protocol: TCP
      port: 8002
      targetPort: 8002
      name: http-gui