apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-collaboration
  labels:
    app: drawn-collaboration-service
spec:
  selector:
    matchLabels:
      app: drawn-collaboration-service
  replicas: 1
  template:
    metadata:
      labels:
        app: drawn-collaboration-service
    spec:
      #initContainers:
      #- name: drawn-collaboration-migrate
      #  image: sorawit12535/drawn-collaboration-service:1.0.5
        # image: werapat002/ms-collaborative:latest
      #  env:
      #  - name: DATABASE_URL
      #    value: mongodb+srv://admin:itHouIC198o1smNK@maincluster.3gkr8.mongodb.net/collaboration?retryWrites=true&w=majority&appName=mainCluster
          # value: "mongodb://admin:admin@mongo:27017/chat?authSource=admin"
      #  command: ["sh", "-c", "npx prisma db push"]
      containers:
      - name: drawn-collaboration-service
        image: sorawit12535/drawn-collaboration-service:1.0.5
        # image: werapat002/ms-collaborative:latest
        ports:
        - containerPort: 8083
        env:
        - name: DATABASE_URL
          value: mongodb+srv://admin:itHouIC198o1smNK@maincluster.3gkr8.mongodb.net/collaboration?retryWrites=true&w=majority&appName=mainCluster
        - name: FIREBASE_API_KEY
          value: AIzaSyAld4dBw6KFg29OOHlAbkEZvXyEU92JVkc
        - name: FIREBASE_AUTH_DOMAIN
          value: drawn-2368b.firebaseapp.com
        - name: FIREBASE_PROJECT_ID
          value: drawn-2368b
        - name: FIREBASE_STORAGE_BUCKET
          value: drawn-2368b.appspot.com
        - name: FIREBASE_MESSAGING_SENDER_ID
          value: "646848533306"
        - name: FIREBASE_APP_ID
          value: 1:646848533306:web:75eaa91377aee9528df603
        - name: REDIS_HOST
          value: redis-server
        - name: REDIS_PORT
          value: "6379"
        - name: WORKSPACE_BACKEND_URL
          value: http://drawn-workspace-management-service:3001

---

apiVersion: v1
kind: Service
metadata:
  name: drawn-collaboration-service
spec:
  type: ClusterIP
  selector:
    app: drawn-collaboration-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
